[profile.default]
src = "src"
out = "out"
libs = ["lib"]

 [rpc_endpoints]
celo-alfajores = "https://alfajores-forno.celo-testnet.org"
celo = "https://forno.celo.org"

#Testing using arb - sepolia as celo l2 stabilizes
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

arbitrumSepolia = "https://sepolia-rollup.arbitrum.io/rpc"

ethereum-holesky = "https://eth-holesky.g.alchemy.com/v2/XpZjXgxfC9_Vww6m81BedcCXi0JbXdx_"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
